### PR TITLE
feat: add NFData instance

### PR DESCRIPTION
**Pull request by guibou**
This is required / desirable for https://github.com/NorfairKing/sydtest/pull/94

### CODE REVIEW

**Comment by NorfairKing** [comment]
We'll need a version bump and a changelog entry so I can release.

**Comment by guibou** [comment]
@NorfairKing should I do that in this MR?

**Comment by guibou** [comment]
@NorfairKing in order to avoid another time consuming ping/pong, I've done a version bump and changelog entry. Tell me if that's according to your requirements and what should be the next steps.

**Comment by NorfairKing** [comment]
Hey @guibou that's perfect! I'll merge this today when I'm on the train.
I've been traveling from Thursday until Today.

**Comment by NorfairKing** [comment]
Merged manually.

**Pull request closed without merging**
